### ISSUE TITLE
 Suggestion for adding OpenCompass to survey

### ISSUE THREAD

**Issue by gaotongxiao** [MLGroupJLU/LLM-eval-survey#11]
Hi team,

Thanks for your awesome survey! I was wondering if you might consider including the [OpenCompass](https://github.com/InternLM/opencompass) evaluation toolkit in your survey. At present, OpenCompass serves as a repository for over 50 benchmarks and enables systematic evaluation of LLMs. We are continually upgrading it to keep pace with the latest evaluation trends. I believe that its addition could provide an even richer context for your survey. 

Best

**Comment by MLGroupJLU** [comment]
Thank you for your interest in our articles.

Coincidentally, we have also noticed your OpenCompass work before, we think it is a good and complete work, and we are also working on including it in our paper.

We will upload an updated version of the paper to arXiv, which may take a while, and look forward to your attention.

**Comment by gaotongxiao** [comment]
It's great to hear that. Thanks for your efforts again! 😀
