### ISSUE TITLE
Add paper, ALIGNING AI WITH SHARED HUMAN VALUES 

### ISSUE THREAD

**Issue by tiansiyuan** [MLGroupJLU/LLM-eval-survey#18]
It is in the references of your paper but not in the Github repository.

https://arxiv.org/pdf/2008.02275.pdf

**Comment by cyp-jlu-ai** [comment]
We have replenished

**Comment by llm172** [comment]
> It is in the references of your paper but not in the Github repository.
> 
> https://arxiv.org/pdf/2008.02275.pdf

We have replenished
