### ISSUE TITLE
Can you add SpyGame to your survey?

### ISSUE THREAD

**Issue by Skytliang** [MLGroupJLU/LLM-eval-survey#26]
Hi there,

Thanks for the effort in putting up this survey on LLMs evaluation.

I'd like to suggest adding our work, SpyGame, a framework for evaluating language model intelligence. We propose to use word guessing games to assess the language and theory of mind intelligences of LLMs.

Paper: [Leveraging Word Guessing Games to Assess the Intelligence of Large Language Models](https://arxiv.org/abs/2310.20499)
GitHub: [https://github.com/Skytliang/SpyGame](https://github.com/Skytliang/SpyGame)

**Comment by YuanWu3** [comment]
Thanks for your valuable contributions, we will include your work in the upcoming version.
