### ISSUE TITLE
Add a new paper.

### ISSUE THREAD

**Issue by Wangpeiyi9979** [MLGroupJLU/LLM-eval-survey#3]
Thank you for your nice survey. 

Please consider adding our recent work, **Large Language Models are not Fair Evaluators** (https://arxiv.org/abs/2305.17926), to the list.

Our research has identified the biases present while using LLM as an evaluator, and we have proposed two strategies to alleviate these biases.

Thanks.😊

**Comment by cyp-jlu-ai** [comment]
Thank you for bringing your recent work to our attention. We appreciate your interest in our survey. We will carefully consider adding your work, "Large Language Models are not Fair Evaluators," to the list of references. Your research is valuable and aligns well with the theme of our survey. We acknowledge the importance of addressing fairness issues in evaluating LLMs and look forward to incorporating your contribution into our work. Thank you once again for your suggestion.

**Comment by cyp-jlu-ai** [comment]
> 感谢您的精彩调查。
> 
> 请考虑将我们最近的工作“**大语言模型不是公平评估者（**https://arxiv.org/abs/2305.17926）”添加到列表中。
> 
> 我们的研究已经确定了使用LLM作为评估器时存在的偏见，我们提出了两种策略来减轻这些偏见。
> 
> 谢谢。😊

Thank you for bringing your recent work to our attention. We appreciate your interest in our survey. We will carefully consider adding your work, "Large Language Models are not Fair Evaluators," to the list of references. Your research is valuable and aligns well with the theme of our survey. We acknowledge the importance of addressing fairness issues in evaluating LLMs and look forward to incorporating your contribution into our work. Thank you once again for your suggestion.

**Comment by llm172** [comment]
> Thank you for your nice survey.
> 
> Please consider adding our recent work, **Large Language Models are not Fair Evaluators** (https://arxiv.org/abs/2305.17926), to the list.
> 
> Our research has identified the biases present while using LLM as an evaluator, and we have proposed two strategies to alleviate these biases.
> 
> Thanks.😊

Thank you for bringing your recent work to our attention. We appreciate your interest in our survey. We will carefully consider adding your work, "Large Language Models are not Fair Evaluators," to the list of references. Your research is valuable and aligns well with the theme of our survey. We acknowledge the importance of addressing fairness issues in evaluating LLMs and look forward to incorporating your contribution into our work. Thank you once again for your suggestion.
