### ISSUE TITLE
Suggestion about adding one evaluation paper about LLMs in science

### ISSUE THREAD

**Issue by taichengguo** [MLGroupJLU/LLM-eval-survey#9]
Thanks for your interesting and comprehensive survey.

If possible, please consider adding our evaluation work about LLMs in chemistry, "What indeed can GPT models do in chemistry? A comprehensive benchmark on eight tasks" (https://arxiv.org/abs/2305.18365) to the list. 

Our work mainly establish a comprehensive benchmark containing 8 practical chemistry tasks to evaluate LLMs (GPT-4, GPT-3.5,and Davinci-003) for each chemistry task in zero-shot and few-shot in-context learning settings. We aim to solve the lack of comprehensive assessment of LLMs in the field of chemistry. 

Thanks!  😊

**Comment by MLGroupJLU** [comment]
Thank you for your interest in our paper.  
Your research is valuable and well done and we plan to include it in our survey.  
After a while, we will upload the updated version of the paper to arXiv, looking forward to your attention.

**Comment by taichengguo** [comment]
Thanks!
